/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
//const sidebars = {
//  // By default, Docusaurus generates a sidebar from the docs folder structure
//  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
//
//  // But you can create a sidebar manually
//  /*
//  tutorialSidebar: [
//    'intro',
//    'hello',
//    {
//      type: 'category',
//      label: 'Tutorial',
//      items: ['tutorial-basics/create-a-document'],
//    },
//  ],
//   */
//};

//export default sidebars;
export default {
  featuresSidebar: [{'🔥 版本新特性':['whatsnew/4', 'whatsnew/3'],},
  'features/intimate',
  {'🌟 特性演示':['features/features_demos/requests', 'features/features_demos/selenium', 'features/features_demos/change_mode',
                'features/features_demos/get_ele_attr', 'features/features_demos/download', ]}
  ],
  usageSidebar: [{
  '💬 入门指南':['get_start/installation', 'get_start/import', 'get_start/before_start',
                {'🌏 上手示例':['get_start/examples/control_browser', 'get_start/examples/data_packets', 'get_start/examples/switch_mode'],
                }, 'get_start/concept'
               ],
  '🚅 SessionPage':['SessionPage/intro', 'SessionPage/create_page_obj', 'SessionPage/visit', 'SessionPage/get_page_info',
                    'SessionPage/get_ele', 'SessionPage/get_ele_info', 'SessionPage/page_settings', 'SessionPage/session_opt'],
  '🛳️ ChromiumPage':['ChromiumPage/intro', 'ChromiumPage/create_page_obj', 'ChromiumPage/visit', 'ChromiumPage/get_page_info',
                     'ChromiumPage/page_operation', 'ChromiumPage/get_ele', 'ChromiumPage/get_ele_info', 'ChromiumPage/ele_operation',
                     'ChromiumPage/waiting', 'ChromiumPage/upload', 'ChromiumPage/tab', 'ChromiumPage/iframe',
                     'ChromiumPage/listener', 'ChromiumPage/actions', 'ChromiumPage/screen', 'ChromiumPage/browser_opt'],
  '🚀 WebPage':['WebPage/intro', 'WebPage/create_page_obj', 'WebPage/mode_change', 'WebPage/function', ],
  '🔎 查找元素':['get_elements/get_ele_intro', 'get_elements/usage', 'get_elements/more',
                'get_elements/simplify', 'get_elements/not_found', 'get_elements/sheet'],
  '⬇️ 下载文件':['download/intro', 'download/DownloadKit', 'download/browser'],
  '🧰 进阶使用':['advance/ini', 'advance/settings', 'advance/commands', 'advance/errors',
                'advance/accelerate', 'advance/packaging', 'advance/tools', 'advance/docking'],
  },
  'MixPage/intro'
  ],
  demoSidebar: ['QandA',
  {'🥬 功能示例':['demos/functions/new_browser','demos/functions/create_browsers','demos/functions/headless',
  'demos/functions/set_cookies'],},
  {'🍔 实战示例':['demos/actual/multithread','demos/actual/multi_browsers',
  'demos/actual/downloadQQ','demos/actual/gitee','demos/actual/maoyan','demos/actual/starbucks',
  'demos/actual/douban',
  {type: 'link',label: '🥗 巡检自动上报(网友投稿)', href: 'https://www.toutiao.com/article/7290179565996343847/'}],
  },
  ],
  historySidebar: ['history/statement', 'history/4x', 'history/3x', 'history/2x', 'history/1x', ]
};